"""Create companies table

Revision ID: 72739c8b86ed
Revises: 
Create Date: 2025-06-06 23:06:21.929385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72739c8b86ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=24), nullable=False))
        batch_op.add_column(sa.Column('metaInfo', sa.JSON(), nullable=True))
        batch_op.drop_column('_id')
        batch_op.drop_column('meta_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_info', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('_id', mysql.VARCHAR(length=24), nullable=False))
        batch_op.drop_column('metaInfo')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
