"""convert_json_to_text

Revision ID: f150f7d2b888
Revises: 72739c8b86ed
Create Date: 2025-06-06 23:19:42.288070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f150f7d2b888'
down_revision = '72739c8b86ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('basicInfo',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('operational',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('contact',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('financials',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('descriptive',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('relationships',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('governance',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('digitalPresence',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('scrapedData',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('metaInfo',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('customSections',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('customSections',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('metaInfo',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('scrapedData',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('digitalPresence',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('governance',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('relationships',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('descriptive',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('financials',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('contact',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('operational',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('basicInfo',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
